stages:
  - build
  - test
  - lint
  - docker
  - deploy
  - notify

build:
  stage: build
  image: python:3.9-slim
  script :
    - echo "Building the application ... "
    - pip install -r requirements.txt

test:
  image: python:3.9
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest

lint :
  stage: lint
  image: python:3.9-slim
  script:
    - echo "Linting the code ... "
    - pip install black
    - black -- check .

docker-build:
  stage: docker
  image: docker:24
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Building Docker image..."
    - docker build -t flask-app .

deploy:
  stage: deploy
  image: python:3.9-slim
  script:
    - echo "Deploying the application ... "

notify:
  stage: notify
  script:
    - echo "Notifying the team ... "
